// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_haylowry.Models;

namespace Mission06_haylowry.Migrations
{
    [DbContext(typeof(MoviesContext))]
    partial class MoviesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_haylowry.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cateogry")
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .HasColumnType("TEXT");

                    b.Property<string>("rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            cateogry = "Action/Adventure",
                            director = "Christopher Nolan",
                            rating = "PG-13",
                            title = "Inception",
                            year = 2010
                        },
                        new
                        {
                            MovieId = 2,
                            cateogry = "Drama",
                            director = "Joe Wright",
                            rating = "PG",
                            title = "Pride & Prejudice",
                            year = 2005
                        },
                        new
                        {
                            MovieId = 3,
                            cateogry = "Comedy",
                            director = "Simon J. Smith",
                            rating = "PG",
                            title = "Bee Movie",
                            year = 2007
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
